version: "3"

services:
    hippotech:
        container_name: hippotech
        image: mtolley/hippotech-java-api:latest
        ports:
            - 3001:3001
        hostname: hippotech
        env_file: .env
        
        environment: 
            APPROVAL_URL: "http://approval:4002"
            BLOG_URL: "http://blog:4003"

    approval:
        container_name: approval
        hostname: approval
        env_file: .env
        image: mtolley/hippotech-approval:latest
        
        environment: 
            JDBC_CONNECTION_STRING: jdbc:h2:mem:demodb
#           FRAUD_URI: "fraud:4004"
            KAFKA_URI: "kafka:9092"
            KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

    credit:
        container_name: credit
        hostname: credit
        image: mtolley/hippotech-credit:latest   

    mongo:
        image: mongo
        container_name: mongo
        hostname: mongo
        restart: always

    # fraud:
    #     container_name: fraud
    #     hostname: fraud
    #     build:
    #         context: ./fraud

    blog:
        container_name: blog
        hostname: blog
        image: mtolley/hippotech-blog:latest
        ports:
            - 4003:4003
        environment: 
            MONGO_URL: "mongodb://mongo:27017"
        depends_on: 
            - mongo

    zookeeper:
        image: confluentinc/cp-zookeeper:5.4.4
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 22181:2181
    
    kafka:
        image: confluentinc/cp-kafka:5.4.4
        depends_on:
            - zookeeper
        ports:
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1