apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit
spec:
  selector:
    matchLabels:
      app: credit
  replicas: 1 
  template:
    metadata:
      labels:
        app: credit
    spec:
      containers:
        - name: credit
          image: mtolley/hippotech-credit:2.0.6
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: hippotech-config
          env:
            - name: JDBC_CONNECTION_STRING
              value: "jdbc:h2:mem:demodb"

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: zookeeper
# spec:
#   selector:
#     matchLabels:
#       app: zookeeper
#   replicas: 1 
#   template:
#     metadata:
#       labels:
#         app: zookeeper
#     spec:
#       containers:
#         - name: zookeeper
#           image: confluentinc/cp-zookeeper:7.0.1
#           imagePullPolicy: IfNotPresent
#           ports:
#             - containerPort: 2181
#           env:  
#             - name: ZOOKEEPER_CLIENT_PORT
#               value: "2181"
#             - name: ZOOKEEPER_TICK_TIME
#               value: "2000"

# ---

# apiVersion: v1 
# kind: Service 
# metadata: 
#   name: zookeeper
# spec:
#   selector:
#     app: zookeeper
#   ports:
#     - protocol: "TCP"
#       port: 2181
#       targetPort: 2181
#   type: ClusterIP
  
# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kafka
# spec:
#   selector:
#     matchLabels:
#       app: kafka
#   replicas: 1 
#   template:
#     metadata:
#       labels:
#         app: kafka
#     spec:
#       containers:
#         - name: kafka
#           image: confluentinc/cp-kafka:7.0.1
#           imagePullPolicy: IfNotPresent
#           ports:
#             - containerPort: 9092
#           env:  
#             - name: KAFKA_BROKER_ID
#               value: "1"
#             - name: KAFKA_ZOOKEEPER_CONNECT
#               value: 'zookeeper-service:2181'
#             - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
#               value: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
#             - name: KAFKA_ADVERTISED_LISTENERS
#               value: PLAINTEXT://:29092,PLAINTEXT_INTERNAL://kafka:9092
#             - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
#               value: "1"
#             - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
#               value: "1"
#             - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
#               value: "1"

# ---

# apiVersion: v1 
# kind: Service 
# metadata: 
#   name: kafka
# spec:
#   selector:
#     app: kafka
#   ports:
#     - protocol: "TCP"
#       port: 9092
#       targetPort: 9092
#   type: ClusterIP
  