apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
spec:
  selector:
    matchLabels:
      app: fraud
  replicas: 1 
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: mtolley/hippotech-fraud:2.0.6
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: hippotech-config
          ports:
            - containerPort: 4004
            - containerPort: 4005

---

apiVersion: v1 
kind: Service 
metadata: 
  name: fraud
spec:
  selector:
    app: fraud
  ports:
    - protocol: "TCP"
      name: port4004
      port: 4004
      targetPort: 4004
    - protocol: "TCP"
      name: port4005
      port: 4005
      targetPort: 4005
  type: NodePort