apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api
spec:
  selector:
    matchLabels:
      app: java-api
  replicas: 1 
  template:
    metadata:
      labels:
        app: java-api
    spec:
      containers:
        - name: java-api
          image: mtolley/hippotech-java-api:2.0.6
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: hippotech-config
          ports:
            - containerPort: 3001
          env:
            - name: BLOG_URL
              value: "http://blog:4003"
            - name: APPROVAL_URL
              value: "http://approval:4002"

---

apiVersion: v1 
kind: Service 
metadata: 
  name: java-api-svc
spec:
  selector:
    app: java-api
  ports:
    - protocol: "TCP"
      port: 3001 
      targetPort: 3001 
  type: NodePort 