name: CI V2 Docker Compose
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  test-compose-action:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      repository-projects: write
      security-events: write
      statuses: write

    env:
      SEEKER_SERVER_URL: ${{ vars.SEEKER_SERVER_URL }}
      SEEKER_PROJECT_KEY: ${{ vars.SEEKER_PROJECT_KEY }}
    
    name: test compose action
    steps:
        - uses: actions/checkout@v3
        - uses: isbang/compose-action@v1.5.1
          with:
            compose-file: "docker-compose.yml"

        - name: Sleep for 30 seconds v1
          uses: jakejarvis/wait-action@master
          with:
            time: '30s'

        - name: Install Cypress
          uses: cypress-io/github-action@v6
          with:
            working-directory: ./hippotech-react
            runTests: false

        - name: Sleep for 15 seconds v2
          uses: jakejarvis/wait-action@master
          with:
            time: '15s'

        - name: Cypress run
          uses: cypress-io/github-action@v4
          with:
            working-directory: ./hippotech-react
            install: false
            continue-on-error: true

        - name: Run Automated Acceptance Tests
          working-directory: ./jest
          run: npm install && npm test
          continue-on-error: true

        - name: List Seeker Vulnerabilities
          uses: mtolley/seeker-github-actions/list-seeker-vulnerabilities@v1.1
          with:
            seekerAPIToken: ${{ secrets.SEEKER_ACCESS_TOKEN }}
            minSeverity: HIGH
            onlySeekerVerified: true

        - name: Seeker Compliance Reporting
          uses: mtolley/seeker-github-actions/seeker-compliance-reporting@v1.1
          with:
            seekerAPIToken: ${{ secrets.SEEKER_ACCESS_TOKEN }}
            generateComplianceReportPDF: true
            failBuildIfNotInCompliance: true  

        - name: Publish Test Report
          uses: mikepenz/action-junit-report@v3
          if: success() || failure() # always run even if the previous step fails
          with:
            report_paths: 'jest/*.xml'

        - name: Get results from Seeker
          uses: lejouni/seeker-report-export@main
          with:
            url: ${{vars.SEEKER_SERVER_URL}}
            token: ${{secrets.SEEKER_ACCESS_TOKEN}}
            project: ${{vars.SEEKER_PROJECT_KEY}}
            format: sarif
            stacktrace: true

        - name: Upload SARIF file
          uses: github/codeql-action/upload-sarif@v2
          with:
            # Path to SARIF file
            sarif_file: ${{github.workspace}}/SeekerResults.sarif.json
            #sarif_file: samplesarif.json
          continue-on-error: false
